# Generated by Django 6.0.4 on 2026-07-30 03:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('placa', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_llegada', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('lugar_embarque', models.CharField(max_length=200)),
                ('lugar_desembarque', models.CharField(max_length=200)),
                ('conductor1_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('conductor1_licencia', models.CharField(blank=True, max_length=50, null=True)),
                ('conductor1_hora_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('conductor1_hora_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('conductor2_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('conductor2_licencia', models.CharField(blank=True, max_length=50, null=True)),
                ('conductor2_hora_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('conductor2_hora_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('conductor3_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('conductor3_licencia', models.CharField(blank=True, max_length=50, null=True)),
                ('incidente1_nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('incidente1_constancia', models.TextField(blank=True, null=True)),
                ('incidente1_firma', models.CharField(blank=True, max_length=100, null=True)),
                ('incidente1_dni', models.CharField(blank=True, max_length=20, null=True)),
                ('incidente2_nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('incidente2_constancia', models.TextField(blank=True, null=True)),
                ('incidente2_firma', models.CharField(blank=True, max_length=100, null=True)),
                ('incidente2_dni', models.CharField(blank=True, max_length=20, null=True)),
                ('incidente3_nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('incidente3_constancia', models.TextField(blank=True, null=True)),
                ('incidente3_firma', models.CharField(blank=True, max_length=100, null=True)),
                ('incidente3_dni', models.CharField(blank=True, max_length=20, null=True)),
                ('incidente4_nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('incidente4_constancia', models.TextField(blank=True, null=True)),
                ('incidente4_firma', models.CharField(blank=True, max_length=100, null=True)),
                ('incidente4_dni', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HorarioFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField(help_text='Ej: 08:00, 10:30')),
                ('dias_semana', models.CharField(default='1,2,3,4,5,6,7', help_text='Días: 1=Lun, 2=Mar, ..., 7=Dom (separados por coma)', max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horario Fijo',
                'verbose_name_plural': 'Horarios Fijos',
                'ordering': ['hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='Manifiesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_viaje', models.DateField()),
                ('conductor_nombre', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=20)),
                ('hora_salida', models.TimeField()),
                ('brevete', models.CharField(max_length=50)),
                ('destino_origen', models.CharField(max_length=100)),
                ('destino_final', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('fidelizacion', 'Fidelización'), ('operativa', 'Operativa'), ('comunicado', 'Comunicado'), ('venta', 'Venta')], max_length=20)),
                ('categoria', models.CharField(choices=[('alerta', 'Alerta'), ('comunicado', 'Comunicado'), ('info', 'Información')], default='alerta', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PasajeroManifiesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('destino', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='sede_asignada',
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='fecha_reserva',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se realizó la reserva', null=True),
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='nombre_reserva',
            field=models.CharField(blank=True, help_text='Nombre del pasajero que reservó', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='nota_reserva',
            field=models.TextField(blank=True, help_text="Ej: 'Paga al llegar', 'Viene con maleta grande'", null=True),
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='numero_documento_reserva',
            field=models.CharField(blank=True, help_text='DNI del pasajero que reservó', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='telefono_reserva',
            field=models.CharField(blank=True, help_text='Celular para notificar llegada', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='calle',
            field=models.CharField(blank=True, help_text='Calle específica para hoja de ruta (ej: Cal. La Cultura S/N)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='categoria_licencia',
            field=models.CharField(blank=True, choices=[('', 'Seleccione categoría...'), ('A-I', 'A-I (Motocicletas)'), ('A-IIA', 'A-IIA (Automóviles particulares)'), ('A-IIB', 'A-IIB (Automóviles públicos - Taxis)'), ('A-IIIa', 'A-IIIa (Buses pequeños < 20 pasajeros)'), ('A-IIIb', 'A-IIIb (Buses medianos 20-50 pasajeros)'), ('A-IIIc', 'A-IIIc (Buses grandes > 50 pasajeros)'), ('B-I', 'B-I (Camionetas ligeras)'), ('B-IIa', 'B-IIa (Camiones medianos)'), ('B-IIb', 'B-IIb (Camiones pesados)'), ('B-IIIa', 'B-IIIa (Camiones articulados)'), ('B-IIIb', 'B-IIIb (Camiones especiales)'), ('C-I', 'C-I (Maquinaria liviana)'), ('C-IIa', 'C-IIa (Maquinaria pesada)'), ('C-IIb', 'C-IIb (Maquinaria especial)')], help_text='Categoría de licencia', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_chofer',
            field=models.BooleanField(default=False, help_text='¿Es chofer activo?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento de licencia', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='licencia_conducir',
            field=models.CharField(blank=True, help_text='Número de licencia de conducir', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rutas_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Rutas que este chofer está autorizado a conducir', related_name='choferes', to='core.ruta'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='chofer_asignado',
            field=models.ForeignKey(blank=True, help_text='Chofer asignado a este vehículo', limit_choices_to={'es_chofer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='rutas_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Rutas que puede realizar este vehículo', related_name='vehiculos', to='core.ruta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón social (empresas)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='ruc_cliente',
            field=models.CharField(blank=True, help_text='RUC del cliente', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='chofer_asignado',
            field=models.ForeignKey(blank=True, help_text='Chofer asignado para este viaje', limit_choices_to={'es_chofer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(choices=[('Sede Trujillo', 'Trujillo'), ('Sede Julcán', 'Julcán'), ('Sede Mache', 'Mache'), ('Oficina Central', 'Sede Central (Dueño)')], max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('username', 'sede'), name='unique_usuario_sede'),
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojas_ruta', to='core.sede'),
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoja_ruta', to='core.viaje'),
        ),
        migrations.AddField(
            model_name='horariofijo',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ruta'),
        ),
        migrations.AddField(
            model_name='horariofijo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehiculo'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifiestos', to='core.sede'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifiesto', to='core.viaje'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='core.sede'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pasajeromanifiesto',
            name='manifiesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajeros', to='core.manifiesto'),
        ),
    ]
