# Generated by Django 6.0.4 on 2026-08-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hojaruta_horariofijo_manifiesto_notificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientoviaje',
            name='reservado_por_chofer',
            field=models.BooleanField(default=False, help_text='Indica si la reserva la hizo un chofer'),
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='tipo_reserva_chofer',
            field=models.CharField(blank=True, choices=[('con_cobro', 'Reserva con Cobro (Chofer ya cobró)'), ('sin_cobro', 'Reserva sin Cobro (Pendiente de pago en sede)')], help_text='Tipo de reserva realizada por el chofer', max_length=20, null=True),
        ),
    ]
