# Generated by Django 6.0.4 on 2026-07-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_unique_usuario_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(choices=[('Sede Trujillo', 'Trujillo'), ('Sede Julcán', 'Julcán'), ('Sede Mache', 'Mache'), ('Oficina Central', 'Sede Central (Dueño)')], max_length=50, unique=True),
        ),
    ]
