# Generated by Django 6.0.4 on 2026-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sede_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria_licencia',
            field=models.CharField(blank=True, help_text='Ej: A-IIA, A-IIIB', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_chofer',
            field=models.BooleanField(default=False, help_text='¿Es chofer activo?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='licencia_conducir',
            field=models.CharField(blank=True, help_text='Número de licencia de conducir', max_length=20),
        ),
    ]
