# Generated by Django 6.0.4 on 2026-08-04 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asientoviaje_reservado_por_chofer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientoviaje',
            options={'ordering': ['numero_asiento'], 'verbose_name': 'Asiento de Viaje', 'verbose_name_plural': 'Asientos de Viaje'},
        ),
        migrations.RemoveConstraint(
            model_name='asientoviaje',
            name='unique_asiento_vendido_por_viaje',
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='chofer_reserva',
            field=models.ForeignKey(blank=True, help_text='Chofer real de la base de datos que hizo la reserva', limit_choices_to={'es_chofer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_reservados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asientoviaje',
            name='fecha_reserva',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la reserva', null=True),
        ),
        migrations.AlterField(
            model_name='asientoviaje',
            name='nombre_reserva',
            field=models.CharField(blank=True, help_text='Nombre del pasajero', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asientoviaje',
            name='nota_reserva',
            field=models.TextField(blank=True, help_text="Ej: 'Paga al llegar', 'Equipaje extra'", null=True),
        ),
        migrations.AlterField(
            model_name='asientoviaje',
            name='numero_documento_reserva',
            field=models.CharField(blank=True, help_text='DNI del pasajero', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asientoviaje',
            name='reservado_por_chofer',
            field=models.BooleanField(default=False, help_text='True si la reserva la hizo un chofer en ruta'),
        ),
        migrations.AlterField(
            model_name='asientoviaje',
            name='telefono_reserva',
            field=models.CharField(blank=True, help_text='Celular del pasajero', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asientoviaje',
            name='tipo_reserva_chofer',
            field=models.CharField(blank=True, choices=[('con_cobro', 'Con Cobro (Chofer ya cobró)'), ('sin_cobro', 'Sin Cobro (Pendiente de pago en sede)')], help_text='Estado del pago de la reserva del chofer', max_length=20, null=True),
        ),
    ]
