# Generated by Django 6.0.4 on 2026-07-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_categoria_licencia_usuario_es_chofer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria_licencia',
            field=models.CharField(blank=True, choices=[('', 'Seleccione categoría...'), ('A-I', 'A-I (Motocicletas)'), ('A-IIA', 'A-IIA (Automóviles particulares)'), ('A-IIB', 'A-IIB (Automóviles públicos - Taxis)'), ('A-IIIa', 'A-IIIa (Buses pequeños < 20 pasajeros)'), ('A-IIIb', 'A-IIIb (Buses medianos 20-50 pasajeros)'), ('A-IIIc', 'A-IIIc (Buses grandes > 50 pasajeros)'), ('B-I', 'B-I (Camionetas ligeras)'), ('B-IIa', 'B-IIa (Camiones medianos)'), ('B-IIb', 'B-IIb (Camiones pesados)'), ('B-IIIa', 'B-IIIa (Camiones articulados)'), ('B-IIIb', 'B-IIIb (Camiones especiales)'), ('C-I', 'C-I (Maquinaria liviana)'), ('C-IIa', 'C-IIa (Maquinaria pesada)'), ('C-IIb', 'C-IIb (Maquinaria especial)')], help_text='Categoría de licencia', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento de licencia', null=True),
        ),
    ]
