# Generated by Django 6.0.4 on 2026-08-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_asientoviaje_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientoviaje',
            name='email_reserva',
            field=models.EmailField(blank=True, help_text='Correo electrónico del pasajero', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='metodo_pago_reserva',
            field=models.CharField(blank=True, help_text='Método de pago: efectivo, yape, plin', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='razon_social_reserva',
            field=models.CharField(blank=True, help_text='Razón social', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='ruc_reserva',
            field=models.CharField(blank=True, help_text='RUC del cliente', max_length=20, null=True),
        ),
    ]
