# Generated by Django 6.0.4 on 2026-08-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_asientoviaje_email_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_correlativo',
            field=models.PositiveIntegerField(blank=True, help_text='Número correlativo del boleto (000001, 000002, etc.)', null=True),
        ),
    ]
