# Generated by Django 6.0.4 on 2026-08-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_venta_numero_correlativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifiesto',
            name='numero_correlativo',
            field=models.PositiveIntegerField(blank=True, help_text='Número correlativo del manifiesto (ej: 1, 2, 3...)', null=True),
        ),
    ]
