# Generated by Django 6.0.4 on 2026-07-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vehiculo_chofer_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='sede_asignada',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='rutas_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Rutas que puede realizar este vehículo', related_name='vehiculos', to='core.ruta'),
        ),
    ]
