# Generated by Django 6.0.4 on 2026-08-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_manifiesto_numero_correlativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaruta',
            name='numero_correlativo',
            field=models.PositiveIntegerField(blank=True, help_text='Número correlativo de la hoja de ruta', null=True),
        ),
    ]
