# Generated by Django 6.0.4 on 2026-07-25 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_vehiculo_sede_asignada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='chofer_asignado',
            field=models.ForeignKey(blank=True, help_text='Chofer asignado para este viaje', limit_choices_to={'es_chofer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
