# Generated by Django 6.0.4 on 2026-07-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_viaje_chofer_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rutas_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Rutas que este chofer está autorizado a conducir', related_name='choferes', to='core.ruta'),
        ),
    ]
