# Generated by Django 6.0.4 on 2026-08-06 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hojaruta_numero_correlativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('total_viajes', models.IntegerField(default=0)),
                ('viajes_pendientes_premio', models.IntegerField(default=0)),
                ('ultimo_viaje_fecha', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente Fidelización',
                'verbose_name_plural': 'Clientes Fidelización',
            },
        ),
        migrations.CreateModel(
            name='PremioFidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ganado', models.DateTimeField(auto_now_add=True)),
                ('fecha_entregado', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(default='Rasca y Gana - 12 viajes', max_length=200)),
                ('entregado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='core.clientefidelizacion')),
            ],
            options={
                'verbose_name': 'Premio Fidelización',
                'verbose_name_plural': 'Premios Fidelización',
            },
        ),
    ]
