# Generated by Django 6.0.4 on 2026-07-27 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usuario_rutas_asignadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField(help_text='Ej: 08:00, 10:30')),
                ('dias_semana', models.CharField(default='1,2,3,4,5,6,7', help_text='Días: 1=Lun, 2=Mar, ..., 7=Dom (separados por coma)', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehiculo')),
            ],
            options={
                'verbose_name': 'Horario Fijo',
                'verbose_name_plural': 'Horarios Fijos',
                'ordering': ['hora_salida'],
            },
        ),
    ]
