# Generated by Django 6.0.4 on 2026-07-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_horariofijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientoviaje',
            name='fecha_reserva',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se realizó la reserva', null=True),
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='nombre_reserva',
            field=models.CharField(blank=True, help_text='Nombre del pasajero que reservó', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='nota_reserva',
            field=models.TextField(blank=True, help_text="Ej: 'Paga al llegar', 'Viene con maleta grande'", null=True),
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='telefono_reserva',
            field=models.CharField(blank=True, help_text='Celular para notificar llegada', max_length=20, null=True),
        ),
    ]
