# Generated by Django 6.0.4 on 2026-07-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_asientoviaje_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin')], default='efectivo', max_length=20),
        ),
    ]
