# Generated by Django 6.0.4 on 2026-07-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_venta_email_cliente_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón social (empresas)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='ruc_cliente',
            field=models.CharField(blank=True, help_text='RUC del cliente', max_length=20, null=True),
        ),
    ]
