# Generated by Django 6.0.4 on 2026-07-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_venta_razon_social_venta_ruc_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientoviaje',
            name='numero_documento_reserva',
            field=models.CharField(blank=True, help_text='DNI del pasajero que reservó', max_length=20, null=True),
        ),
    ]
